### PR TITLE
Add version upgrade constraints

### PR DESCRIPTION
**Pull request by kamolhasan**
Signed-off-by: kamolhasan <kamol@appscode.com>

### CODE REVIEW

**Review by raihankhan — DISMISSED** [review]
LGTM!

**Review by ArnobKumarSaha — CHANGES_REQUESTED** [review]
Why we need to use the `DenyList` ? 
A version that is not in the `AllowList` should be considered as denied. And a `*` in AllowList will refer all versions to be allowed.

**Comment by tamalsaha** [comment]
> Why we need to use the `DenyList` ? A version that is not in the `AllowList` should be considered as denied. And a `*` in AllowList will refer all versions to be allowed.

The idea was that a version is allowed if it is in Allow List and Not in Deny List. So, you can allow all and then deny specific versions. This is just to make things easier / more flexible.

**Review by faem — APPROVED** [review]

**Review by rakibulhossain — APPROVED** [review]
LGTM!

**Review by ArnobKumarSaha — APPROVED** [review]

**Pull request merged**
